### ISSUE TITLE
🎙 talk.js - May 2019

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/talk.js#22]
### 📝 Details
- [x] Event: [talk.js](https://www.meetup.com/Singapore-JS/events/261291636/)
- [x] Date: 15 May (Wed)
- [x] Hosts: @ongmin
- [x] Venue: Microsoft Level 22
- [x] Food Sponsor: SPH

### 📅 Agenda

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over 🍕_
7.30pm | Start of event - _opening segment by host_
7.40pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

### :speech_balloon: Talks

- [ ] My Awesome Talk by _You_

### :seedling: Propose a talk this month

Want to speak at this month's talk? Leave a comment below with the following details:

<details>
<summary>Click for details</summary>

> #### Title of your topic
> Insert catchy title here
>
> #### Topic description
> Tell us what you'd like to talk about
>
> #### Presenter(s)
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> #### Presenter's bio
> A short introduction of yourself
>
> #### Duration
> 5 minutes for presenting an introduction to the topic, then up to 20 minutes for discussion.
>
> #### Deck URL (if any)
> You can add this part in later

</details>

### :loudspeaker: Open announcements
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist

<details>
<summary>Click for details</summary>

- [x] Check available dates on [EngineersSG](https://engineers.sg/)
- [x] Confirm date and venue availability
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [x] Prepare deck for event

\* _checked boxes indicate confirmed/done_

</details>

**Comment by anontyro** [comment]
### Title of your topic
An Overview of GraphQL Front + Backend

### Topic description
GraphQL has been steadily growing in popularity over the past few years  as a way to bring together the ever more fractured ecosystem into one neat focal point. GraphQL is easy to setup and works fantastically across a variety of languages and platforms. 

In this talk I hope to outline GraphQL and pull out some examples to hopefully illustrate why you should dive right into this new paradigm. 

I will be talking about GraphQL largely using the Apollo framework with Typescript.

Content:
- What is GraphQL
- Why should I use GraphQL
- GraphQL ServerSide
- GraphQL ClientSide
- Example
- Alternatives

### Presenter
[ME!](https://github.com/anontyro)
I'm Alex! I work as a frontend developer at [Hooq](https://hooq.tv) tackling the thrills of ReactJS with a keen interest in all things (Java || Type)script! In my free time I enjoy playing with new fun things like [Rust](https://www.rust-lang.org/) and generally making weird things!

### Duration
35 minutes + 5 minutes QA

**Comment by duquesnay** [comment]
### Title of the topic
Tough Talks, or How to confront opinions with your teammates

### Topic Description
Be it in software development, product management, or any kind of team work, the ability to confront opinions is key to be a great team or a great company. This topic kept coming back as I was interviewing the most respected developers I knew a couple of years ago in Paris. If you don’t confront opinions, you are not really using all the talents. Now, it’s not easy. 
I synthesised and structured what I learnt in these interviews, and I‘d like to share what I learnt:

* how to know your idea is actually a good one
* what are the diplomatic baselines for disagreeing
* when to hold your position and when to change your mind
* how to learn to be wrong
* what if people’s positions are locked?

### Presenter
Hi, I'm Giom
* Original Frenchman, came to South East Asia in 2015
* I'm based in Singapore, work as an independent
* I help business transform how people work together, through Agile coaching, training and facilitation
* I've been a coder since childhood and it was my main activity until 10 years ago when coaching took over
* I still do roleplaying games at 42y old
* I do lots of other stuff and I'm passionate about many other stuff

### Duration
20 to 30 minutes

**Comment by deepakshrma** [comment]
## Micro FrontEnd
Overview of micro frontend, Different concepts, and Adaptation

### Topic Description
High-level design and architecture of micro frontend. Splitting of the giant code base in small pieces(modules) using mono repo. Use a universal app(SSR) to build an app.

#### Agenda[DRAFT VERSION]

1. High-level overview
2. Architecture
3. Code/Project explanation
4. Demo of working app

## [TODO] This is just a draft version, not completed yet! Thanks for the support. 🙏

**Comment by ongmin** [comment]
Hi @anontyro and @duquesnay! Thanks for these two awesome topics!

@anontyro Is it possible to adapt it to 25 minutes + 10 minutes Q&A? It's just to make sure we work with the natural attention span of people for absorbing knowledge after a day of work and a stomach full of pizza..

@duquesnay If you're up for it, since this is a non-tech topic, what do you think about keeping the presentation bit for 15-20 minutes and then opening it to the floor for a discussion after? Something for the audience to share situations they have been in and ask both you and also others for their experience? For more sharing and exchange.

We'll probably just keep it to this two talks for May so we have time to go deep as the mood of the people goes. :)

**Comment by anontyro** [comment]
@ongmin Sure I can shorten it a bit shouldn't be a problem :)

**Comment by duquesnay** [comment]
Doable! I have to think of questions for the audience, unless you have some. 

Giom

**Comment by ongmin** [comment]
If you're interested, videos for these two talks can be found:

1. Tough Talks, or How to confront opinions with your teammates (by Giom)
https://engineers.sg/video/singaporejs-talk-js-chat-js-may--3360

2. An Overview of GraphQL Front + Backend (by Alexander Wilkinson)
https://engineers.sg/video/singaporejs-talk-js-chat-js-may-part-2--3359

Thanks again for speaking and attending! :)
